[tool.poetry]
name = "henonfunction"
version = "0.1.0"
description = ""
authors = ["greggelong <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
matplotlib = "^3.4.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
